sudo: required
services:
  - docker

before_install:
  - "sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest"
  - "sudo chmod +x /usr/local/bin/ecs-cli"
  - "ecs-cli configure --region us-west-2 --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY --cluster ecs-hacko"
script:
  - docker-compose run web python manage.py test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t pdxdiver/django-web .
    docker login -user "$DOCKER_USERNAME" -password "$DOCKER_PASSWORD";
    docker push pdxdiver/django-web;
    fi
  - "ecs-cli compose --project-name ecs-hacko--user --file ecs-deploy.yml service up"
